### ISSUE TITLE
Remove this repository

### ISSUE THREAD

**Issue by WinterMute** [T3CHNOLOG1C/ActualBrickingTool#1]
This is just completely irresponsible and serves no purpose whatsoever.

Please remove it.

**Comment by ClammyMantis488** [comment]
Why should they remove it?

**Comment by kekmaster97** [comment]
No purpose? It's clearly the next-level application for the 3DS.

**Comment by Helloman892** [comment]
@WinterMute To be fair, anyone retarded enough to use this without being prepared for it *deserves* the brick.

**Comment by mattkenster** [comment]
rEmOvE tHiS rEpOsItOrY

tHiS Is jUsT CoMpLeTeLy iRrEsPoNsIbLe aNd sErVeS No pUrPoSe wHaTsOeVeR.
pLeAsE ReMoVe iT

**Comment by WinterMute** [comment]
@Helloman892 even when some idiot takes this code & disguises it "for a laugh"?

**Comment by mattkenster** [comment]
EvEn wHeN SoMe iDiOt tAkEs tHiS CoDe & dIsGuIsEs iT "fOr a lAuGh"?

**Comment by Helloman892** [comment]
@WinterMute Ok, and let's assume this repo *does* get deleted - what do we do the next time someone (perhaps someone more irresponsible?) decides to create a 'bricking tool', but this time, they don't give it a name like 'ActualBrickingTool'?

**Comment by WinterMute** [comment]
@Helloman892 this repo makes that inevitable, or at least more inevitable than before this repo was made public.

**Comment by astronautlevel2** [comment]
Granted, all this does is delete NFIRM and a few other firms, which is stupid easy to repair - however, that still doesn't change the fact that this code is pointless and malicious. @WinterMute is exactly correct that someone _will_ use this in a fake leak or fake homebrew, and even if it can't be delayed inevitably, no reason to make it easy.

**Comment by mattkenster** [comment]
In what way does this repo make it any more inevitable than it already is? I struggle to understand your point

**Comment by astronautlevel2** [comment]
Because before, the only people who could make a bricker tool are people who at least kind of sort of understood code. Now, any random who stumbles across this repo and wants to make a bricker tool can change a few files, delete a line or two for checks, and then have it.

**Comment by Helloman892** [comment]
@WinterMute Given what Alex has said, and considering that my response to this was mostly a stupid meme *regardless*, I'll concede here.

**Comment by T3CHNOLOG1C** [comment]
I have absolutely no knowledge of C and was able to make this by looking at the examples, 3dbrew, and the documentation. This is not going to be deleted.
