### ISSUE TITLE
how can i recover from 11.3

### ISSUE THREAD

**Issue by lucario1001** [T3CHNOLOG1C/ActualBrickingTool#2]
pls halp i bricked from your tool

i have no backup
i have no sex life 
i need friends :(
please help

**Comment by kekmaster97** [comment]
instal fefosheep!!

**Comment by T3CHNOLOG1C** [comment]
if you didn't have a backup and didn't listen to the clearly visible warnings, you deserve the brick tbh 😂 🔫 👌
